[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[[tool.mypy.overrides]]
module = [
    'scipy',
    'scipy.stats',
    'scipy.special'
    ]
ignore_missing_imports = true

[tool.isort]
profile = "black"
